### ISSUE TITLE
hts_engine problem when running HTS-demo_CMU-ARCTIC-SLT

### ISSUE THREAD

**Issue by hodhod88** [celsius/hts-engine#1]
Hi,
I’m training the HTS-demo_CMU-ARCTIC-SLT with my own data (raw files, label files and question files), in the beginning everything seems ok, but at the stage of synthesizing waveforms using hts_engine a problem come out which is :

=================================================================================
Start synthesizing waveforms using hts_engine at خ أكت 12 16:11:06 CET 2017
=================================================================================

Synthesizing a speech waveform from /home/nadia/T/HTS-demo_CMU-ARCTIC-SLT/data/labels/gen/alice01.lab using hts_engine...Error: HTS voices cannot be loaded.
Error in /usr/local/bin/hts_engine -m /home/nadia/T/HTS-demo_CMU-ARCTIC-SLT/voices/qst001/ver1/cmu_us_arctic_slt.htsvoice  -or /home/nadia/T/HTS-demo_CMU-ARCTIC-SLT/gen/qst001/ver1/hts_engine/alice01.raw -ow /home/nadia/T/HTS-demo_CMU-ARCTIC-SLT/gen/qst001/ver1/hts_engine/alice01.wav -ot /home/nadia/T/HTS-demo_CMU-ARCTIC-SLT/gen/qst001/ver1/hts_engine/alice01.trace /home/nadia/T/HTS-demo_CMU-ARCTIC-SLT/data/labels/gen/alice01.lab

How can i solve this problem, thank you for your help in advance.

**Comment by celsius** [comment]
Hi,

My guess is that you're using versions of HTS demo and hts-engine that are not compatible with each other.

Also this is not the official repository of hts-engine, only an unofficial clone of their CVS repository, so there won't be any support or any issue fixed here (that's why I'm closing the issue, it doesn't mean that your issue is invalid). Please use the mailing-lists and website of HTS demo and hts-engine for support. 

The mailing list for HTS demo is linked at http://hts.sp.nitech.ac.jp/
The mailing list for hts-engine is linked at: http://hts-engine.sourceforge.net/
